sudo: required
services:
  - docker

before_install:
  - docker build -t rosslutsch/docker-react -f Dockerfile.dev .

script:
  - docker run rosslutsch/docker-react  npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker-react"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-us-east-2-379868135075"
  bucket_path: "docker-react"
  
  access_key_id:
    secure: "$AWS_ACCESS_KEY"
  secret_access_key:
    secure : "$AWS_ACCESS_SECRET"
  on:
    branch: master
